CREATE TABLE IF NOT EXISTS `tb_account_consumer` (
    `key_id` int NOT NULL AUTO_INCREMENT COMMENT '表主键',
    `uid` varchar(19) NOT NULL COMMENT '客户UID',
    `owner_user_uid` varchar(19) NOT NULL COMMENT '归属账号UID',
    `name` varchar(64) NOT NULL COMMENT '客户名称',
    `alias` varchar(64) NULL COMMENT '客户别名',
    `brand_key_id` int NOT NULL COMMENT '财务品牌主键',
    `currency` varchar(16) NOT NULL COMMENT '财务币种编码',
    `email` varchar(128) NOT NULL COMMENT '邮箱',
    `phone` varchar(32) NULL COMMENT '电话号码',
    `status` varchar(32) NOT NULL COMMENT '客户状态：disable=禁用（客户账号不可用）；enable=启用（客户账号正常使用）',
    `pay_mode` varchar(32) NOT NULL COMMENT '付款模式：postpaid=后付（账期后付费）；prepaid=预付（账户预付费）',
    `class_type` varchar(32) NOT NULL DEFAULT 'common' COMMENT '客户类型：common=普通客户（普通业务客户）；cooperate=推广客户（合作推广客户）',
    `balance` bigint NOT NULL DEFAULT 0 COMMENT '余额（放大百万倍存储）',
    `balance_usd` bigint NOT NULL DEFAULT 0 COMMENT 'USD余额（放大百万倍存储）',
    `credit` bigint NOT NULL DEFAULT 0 COMMENT '信用额度（放大百万倍存储）',
    `credit_usd` bigint NOT NULL DEFAULT 0 COMMENT 'USD信用额度（放大百万倍存储）',
    `level` int NOT NULL DEFAULT 1 COMMENT '客户等级',
    `stage` varchar(32) NOT NULL DEFAULT 'cluetrail' COMMENT '客户阶段：authenticate=认证阶段（客户正在认证）；charge=充值阶段（客户准备充值）；cluetrail=线索阶段（客户处于线索跟进）；cooperate=价值阶段（客户已形成稳定价值）；intention=意向阶段（客户已有合作意向）；production=生产阶段（客户已进入生产）；testing=测试阶段（客户正在业务测试）',
    `auth_status` varchar(32) NOT NULL DEFAULT 'unverified' COMMENT '认证状态：pending=认证中（认证资料审核中）；rejected=认证失败（认证资料未通过）；unverified=未认证（尚未提交认证）；verified=已认证（认证已通过）',
    `source` varchar(32) NOT NULL DEFAULT 'manual' COMMENT '注册来源：manual=手动创建（管理端人工创建）；platform=平台注册（客户从平台注册）',
    `remark` varchar(1024) NULL COMMENT '备注',
    `create_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    `modify_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
    PRIMARY KEY (`key_id`),
    UNIQUE KEY `uk_tb_account_consumer_uid` (`uid`),
    KEY `idx_tb_account_consumer_owner_user_uid` (`owner_user_uid`),
    KEY `idx_tb_account_consumer_brand_key_id` (`brand_key_id`),
    KEY `idx_tb_account_consumer_status` (`status`),
    KEY `idx_tb_account_consumer_currency` (`currency`)
) ENGINE = InnoDB AUTO_INCREMENT = 5181000 DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '外部客户账号表';
