CREATE TABLE IF NOT EXISTS `tb_crm_sms_quote_draft` (
    `key_id` int NOT NULL AUTO_INCREMENT COMMENT '表主键',
    `draft_batch_id` varchar(36) NOT NULL COMMENT '草稿批次ID',
    `consumer_key_id` int NOT NULL COMMENT 'Account 客户主键',
    `application_key_id` int NOT NULL COMMENT 'CRM 短信应用主键',
    `app_id` varchar(32) NOT NULL COMMENT '应用ID快照',
    `client_alias` varchar(64) NULL COMMENT '客户别名快照',
    `app_alias` varchar(64) NOT NULL COMMENT '应用别名快照',
    `country_key_id` int NOT NULL COMMENT 'Finance 国家/地区主键',
    `code` varchar(10) NOT NULL COMMENT '国家/地区国际区号',
    `mcc` varchar(4) NOT NULL COMMENT '移动国家代码',
    `up_usd` bigint NOT NULL COMMENT '上行短信售价USD（放大百万倍存储）',
    `down_usd` bigint NOT NULL COMMENT '下行短信售价USD（放大百万倍存储）',
    `currency` varchar(16) NOT NULL COMMENT '报价币种',
    `up_local` bigint NOT NULL COMMENT '上行短信本币售价（放大百万倍存储）',
    `down_local` bigint NOT NULL COMMENT '下行短信本币售价（放大百万倍存储）',
    `exchange_rate` decimal(16, 6) NOT NULL COMMENT 'USD 到报价币种汇率',
    `exchange_date` date NOT NULL COMMENT '汇率日期',
    `effective_time` datetime(3) NULL COMMENT '生效时间',
    `expiry_time` datetime(3) NULL COMMENT '失效时间',
    `source` varchar(32) NOT NULL COMMENT '报价来源：addition=新增（本次新增的国家或地区报价）；existing=已有（从现有有效报价复制）',
    `status` varchar(32) NOT NULL COMMENT '报价草稿状态：active=编辑中（草稿可以继续编辑）；deleted=已删除（草稿已被移除）',
    `remark` varchar(1024) NULL COMMENT '备注',
    `create_by` varchar(19) NOT NULL COMMENT '创建账号UID',
    `modify_by` varchar(19) NULL COMMENT '更新账号UID',
    `create_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    `modify_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
    PRIMARY KEY (`key_id`),
    UNIQUE KEY `uk_tb_crm_sms_quote_draft_batch_country` (`draft_batch_id`, `country_key_id`),
    KEY `idx_tb_crm_sms_quote_draft_consumer_app` (`consumer_key_id`, `application_key_id`),
    KEY `idx_tb_crm_sms_quote_draft_status` (`status`),
    KEY `idx_tb_crm_sms_quote_draft_create_by` (`create_by`)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = 'CRM 短信报价草稿表';
